<?php

/**
 * @file
 * Small modifications made by 3Mules.
 * justin@3mules.coop
 */

/**
 * Implements hook_form_alter() specific to user_register.
 */
function mods_by_3mules_form_user_register_alter(&$form, &$form_state) {

  $original_help_text = $form['user_registration_help']['#value'];

  $form['user_registration_help']['#value'] =
    '<div class="publisher-reg-hint">' .
    '<strong>Note</strong>: If you are a literary agent or a publisher then please <a href="/apply-publisher-account">apply for a publisher account</a> rather than using this form.'
    . '</div>';

  if ( $original_help_text ) {
    $form['user_registration_help']['#value'] .= '<br />' . $original_help_text;
  }
}

/**
 * Implements hook_form_alter() specific to views_exposed_form.
 */
function mods_by_3mules_form_views_exposed_form_alter(&$form, &$form_state) {

  // Make all input boxes the same size and add useful hints.
  $form['search_terms']['#size'] = 20;
  $form['search_terms']['#description'] = t('Enter any keywords');
  $form['author']['#size'] = 20;
  $form['author']['#description'] = t('Enter comma separated user names');
  $form['genre']['#size'] = 20;
  $form['genre']['#description'] = t('Enter a genre name');
}

/**
 * Implements hook_form_alter() specific to word_node_form.
 */
function mods_by_3mules_form_word_node_form_alter(&$form, &$form_state) {

  // Pasting from word can mangle punctuation characters. Give the user
  // some advice.
  $form['body_field']['word-hint']['#weight'] = -50;
  $form['body_field']['word-hint']['#value'] =
    '<div id="word-paste-hint">' .
    t('If you have trouble pasting from Microsoft Word (e.g. mangled punctuation characters) then try using the "Paste from Word" and/or "Paste as Plain Text" buttons.')
    .'</div>';

  // There is no UI to make teaser different from start of synopsis, so
  // the relevant checkbox is probably meaningless to the user. Remove it.
  unset( $form['body_field']['teaser_include'] );
  $form['body_field']['teaser_include']['#value'] = '<!-- Removed teaser_include checkbox in ' . __FUNCTION__ . '-->';
}

/**
 * Implements generic hook_form_alter()
 *
 * This hook gets called *after* the form-specific hook on D6, which is
 * the only reason that I've implemented it.
 */
function mods_by_3mules_form_alter(&$form, &$form_state, $form_id) {

  switch ( $form_id ) {
    case 'word_node_form' :

      // Only admins get to upload attachments to the Word content type now
      // that this feature is deprecated.
      if ( ! user_access( 'administer nodes' ) ) {
        unset( $form['group_chapter'] );
        $form['group_chapter']['#value'] = '<!-- Removed chapter upload fieldset for non-admins in ' . __FUNCTION__ . '-->';
      }
      break;
  }
}

/**
 * Implement preprocess page function.
 */
function mods_by_3mules_preprocess_page(&$vars) {

  // Are we on the top level search page?
  if ( arg(0) == 'search'  &&  !arg(1) ) {

    // Remove the "user" and "node" tabs so that we don't confuse our users.
    unset( $vars['tabs'] );
  }
}

